package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
//import charts.PieChart;
import javax.swing.LayoutStyle;

import charts.PieChart;
import charts.Slice;
import core.DateToMilliSeconds;
import core.Expenses;
import core.Income;
import core.Reminder;
import core.Saving;
import core.Time;
import exceptions.NegativeSecondsException;
import exceptions.NoSuchDateException;
import exceptions.NoSuchTimeException;
import keeper.DataItem;
import keeper.DataSet;

/**
	HomePanel - creates the graphics user interface for home
	
	@authors 	Fuad Aghazada 
				Fatih Özgür Ardıç 
				Babanazar Gutlygeldiyev 
				Haya Shamim Khan Khattak 
				Orcan Yazıcı
	@version 1.00 
*/

public class HomePanel extends JPanel
{
	//class variables
	private static final long serialVersionUID = 1L;
	   // Variables declaration - do not modify                     
    private static JButton addExpense;
    private static JButton addIncome;
    private JButton addReminder;
    private JPanel jPanel1;
    private JLabel label1;
    private JLabel label2;
    private static JLabel label3;
    private static JLabel label4;
    private JLabel label5;
    private static JProgressBar progressBar1;
    private static JProgressBar progressBar2;
    private static DefaultListModel<String> model;
    private JList<String> reminderList;
    private JScrollPane scroll_pane;
    private static JComboBox<String> timely;
    private JLabel reminder;
    private Calendar cal;
    
    private static double percentage1 = 0, percentage2 = 0;
        
	private static PieChart pieChart1;
	private static ArrayList<Slice> slices;
	
	private static ArrayList<Reminder> reminders;
    // End of variables declaration 
    
	public HomePanel()
	{	
		this.initComponents();
		this.modify();
		this.locate();
		this.listen();
		this.setVisible(true);
		this.readFromFile();
	}
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                        
    private void initComponents() 
    {

        label1 = new JLabel();
        timely = new JComboBox<>();
        label2 = new JLabel();
        addIncome = new JButton();
        addExpense = new JButton();
        jPanel1 = new JPanel();   
        progressBar1 = new JProgressBar();
        progressBar2 = new JProgressBar();
        label3 = new JLabel();
        label4 = new JLabel();
        scroll_pane = new JScrollPane();
        label5 = new JLabel();
        reminder = new JLabel();
        addReminder = new JButton();
        model = new DefaultListModel<String>();
        reminderList = new JList<>(model);
        cal = new GregorianCalendar();
        
        slices = new ArrayList<>();
        
        slices.add(new Slice(0, Color.GREEN));
        slices.add(new Slice(0, Color.RED));
        slices.add(new Slice(0, Color.YELLOW));
               
        pieChart1 = new PieChart(slices);
        
        reminders = new ArrayList<>();
        
    }// </editor-fold>
    
    /**
      	Method modify for adjusting or changing some properties of the components
     */
    private void modify()
    {
    	label1.setText("Your");

        timely.setModel(new DefaultComboBoxModel<>(new String[] { "total", "yearly", "monthly", "daily" }));

        label2.setText("budget breakdown");

        addIncome.setText("Add Income");

        addExpense.setText("Add Expense");
        
        addReminder.setIcon(new ImageIcon("images//bell_icon.png"));
          
        jPanel1.setBackground(new Color(138, 138, 138));
        jPanel1.setToolTipText("[Green] - Expenses  [Red] - Incomes  [Yellow] - Savings");
        
        label3.setFont(new Font("Lucida Grande", 0, 10)); // NOI18N
        label3.setText("You have achieved " + percentage1 + "% of your savings goal");

        label4.setFont(new Font("Lucida Grande", 0, 10)); // NOI18N
        label4.setText("You have achieved " + percentage2 + "% of your expenditure limit");

        scroll_pane.setViewportView(reminderList);

        label5.setFont(new Font("Lucida Grande", 1, 20)); // NOI18N
        label5.setText("REMINDERS");

        getPieChart().setPreferredSize(new Dimension(186,186));
          
        reminder.setFont(new Font("Lucida Grande", 2, 9));
        reminder.setText("*Click the bell to add reminder");
    }
    
    /**
      	Method locate for locating the containers and the components on the panel
     */
    private void locate() 
	{
    	GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        
        jPanel1.setBackground(new Color(238,238,238));
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setFocusable(true);
        jPanel1.add(getPieChart(), BorderLayout.CENTER);
        
		GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timely, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label4)
                        .addGap(22, 22, 22))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(progressBar2, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(progressBar1, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
                                .addComponent(label3, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
                            .addComponent(reminder)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addIncome, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addExpense, GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addReminder, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(scroll_pane, GroupLayout.PREFERRED_SIZE, 433, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(label5)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(timely, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(reminder))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addIncome, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addReminder, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addExpense, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(label3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(label5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_pane, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
	}
    
    /**
      	Make the components listenable
     */
    
    private void listen()
    {
    	addReminder.addActionListener(new ActionHandler()); 
    	timely.addActionListener(new ActionHandler());
    }
    
    private void readFromFile()
    {
    	DataSet ds = new DataSet("Reminders.txt");
    	
    	ds.readFromFile2();
    	ArrayList<DataItem> readDataItem = ds.getDataItems();
		System.out.println(readDataItem.size());
		
    	int a = 1;
    	
    	for(DataItem eachDataItem : readDataItem)
    	{
    		String[] fullDate = eachDataItem.getDate().split("/");
    		String[] fullTime = eachDataItem.getTime().split(":");
    		
    		String category = eachDataItem.getCategory();
    		
    		double amount = Double.parseDouble(eachDataItem.getAmount());
    		
    		int day = Integer.parseInt(fullDate[0]);
    		int month = Integer.parseInt(fullDate[1]);
    		int year = Integer.parseInt(fullDate[2]);
    		int hour = Integer.parseInt(fullTime[0]);
    		int minute = Integer.parseInt(fullTime[1]);
    		
    		DateToMilliSeconds d = null;
			
			try
			{
				d = new DateToMilliSeconds(new Time(day, month, year), hour, minute);
			} 
			catch (NoSuchDateException e1) 
			{
				e1.printStackTrace();
			}
			
			long milliseconds = d.convert();
    		
			System.out.println("I am hereeeeeeeee " + milliseconds);
			
			if(milliseconds > 0)
			{
				try 
	    		{
					Reminder reminder = new Reminder(milliseconds, a, category, amount, new Time(day, month, year), hour, minute);
					reminders.add(reminder);
					model.addElement(reminder.toString());
				
				} 
	    		catch (NegativeSecondsException e) 
	    		{
					e.printStackTrace();
				} 
	    		catch (NoSuchDateException e)
	    		{
					e.printStackTrace();
				}
			}
			else
			{
				JOptionPane.showMessageDialog(MainFrame.getFrame(), "You had a reminder of " 
											+ "[" +category + "] in " + day + "/" + month+ "/" + year + " [" + hour + ":" + minute +"]");
			}
    		a++;
    	}
    }
    
    public void writeToFile()
	{
		DataSet ds = new DataSet("Reminders.txt");
		
		ds.prepareToWrite();
		
		for(Reminder data : reminders)
		{
			String date;
			date = 	"" +  data.getTime().getDay();
			date += "/" + data.getTime().getMonth();
			date += "/" + data.getTime().getYear();
			
			String time = "";
			time += "" + data.getHour();
			time += ":" + data.getMinute();
			
			ds.add(data.getCategory(), data.getAmount() + "", date, time);
		}
		
		ds.writeToFile2();
	}

    /**
      	Inner class for action listener
     */
    private class ActionHandler implements ActionListener
    {
    	
		@Override
		public void actionPerformed(ActionEvent e) 
		{
			int a = reminders.size() + 1;
			if(e.getSource() == addReminder)
			{
				try
				{
					JOptionPaneMultiInput jp = new JOptionPaneMultiInput("Add Reminder", 4);
					String amountTxt = jp.getTxtf1().getText();
					String category = jp.getTxtf2().getText();
					
					int day = jp.getDay();
					int month = jp.getMonth();
					int year = jp.getYear();
					
					int hour = jp.getHour();
					int minute = jp.getMinute();
					
					double amount = Double.parseDouble(amountTxt);
					
					System.out.println(category + "" + amount + "\n" + day + "/" + month  + "/" + year +"/\n" + hour + ":" + minute);
					
					
					DateToMilliSeconds d = null;
					
					try
					{
						d = new DateToMilliSeconds(new Time(day, month, year), hour, minute);
					} 
					catch (NoSuchDateException e1) 
					{
						e1.printStackTrace();
					}
					
					long milliseconds = d.convert();
					
					Reminder reminder = null;
					try {
						reminder = new Reminder(milliseconds, a, category, amount, new Time(day, month, year), hour, minute);
					} catch (NoSuchDateException e1) {
						
						e1.printStackTrace();
					}
					reminders.add(reminder);
					
					JOptionPane.showMessageDialog(MainFrame.getFrame(), "Reminder is scheduled!"); 
					
					model.addElement(reminder.toString());
					
					a++;
				}
				catch(NumberFormatException e1)
				{
					System.out.print(e1.getMessage());
					JOptionPane.showMessageDialog(MainFrame.getFrame(), "Wrong input types!", "ERROR", 1);
				} 
				catch (NoSuchTimeException e1) 
				{
					System.out.print(e1.getMessage());
					JOptionPane.showMessageDialog(MainFrame.getFrame(), "Wrong input types!", "ERROR", 1);
				}
				catch (NegativeSecondsException e1) 
				{
					JOptionPane.showMessageDialog(MainFrame.getFrame(), e1.getMessage(), "ERROR", 1);
				}
				
			}
			
			//Listener for combo box
			
			else if(e.getSource() == timely)
			{
				if(timely.getSelectedItem().equals("daily"))
				{
					int currentDay = cal.get(Calendar.DAY_OF_MONTH);
					int currentMonth = cal.get(Calendar.MONTH) + 1;
					int currentYear = cal.get(Calendar.YEAR);
					
					double dailyExpenses = Expenses.getObject().dailyTotalExpenses(currentDay, currentMonth, currentYear);
					double dailyIncomes = Income.getObject().dailyTotalIncomes(currentDay, currentMonth, currentYear);
					double dailySavings = Saving.getObject().dailyTotalSaving(currentDay, currentMonth, currentYear);
					
					pieChart1.getSlices().get(0).setValue(dailyExpenses);
					pieChart1.getSlices().get(1).setValue(dailyIncomes);
					pieChart1.getSlices().get(2).setValue(dailySavings);
					pieChart1.repaint();
					
				}
				else if(timely.getSelectedItem().equals("monthly"))
				{
					int currentMonth = cal.get(Calendar.MONTH) + 1;
					int currentYear = cal.get(Calendar.YEAR);
					
					double monthlyExpenses = Expenses.getObject().monthlyTotalExpenses(currentMonth, currentYear);
					double monthlyIncomes = Income.getObject().monthlyTotalIncomes(currentMonth, currentYear);
					double monthlySavings = Saving.getObject().monthlyTotalSaving(currentMonth, currentYear);
					
					pieChart1.getSlices().get(0).setValue(monthlyExpenses);
					pieChart1.getSlices().get(1).setValue(monthlyIncomes);
					pieChart1.getSlices().get(2).setValue(monthlySavings);
					pieChart1.repaint();
					
				}
				else if(timely.getSelectedItem().equals("yearly"))
				{
					int currentYear = cal.get(Calendar.YEAR);
					
					double yearlyExpenses = Expenses.getObject().yearlyTotalExpenses(currentYear);
					double yearlyIncomes = Income.getObject().yearlyTotalIncomes(currentYear);
					double yearlySavings = Saving.getObject().yearlyTotalSaving(currentYear);				
					
					pieChart1.getSlices().get(0).setValue(yearlyExpenses);
					pieChart1.getSlices().get(1).setValue(yearlyIncomes);
					pieChart1.getSlices().get(2).setValue(yearlySavings);
					pieChart1.repaint();
					
				}
				else if(timely.getSelectedItem().equals("total"))
				{
					updatePieChart();
				}
			}
			
		}
    	
    }
    
    public static void updateProgressBar1()
    {
    	double result = SavingsPanel.getGoalAch();
    	
    	if(result <= 100)
    	{
    		setPercentage1(result);
    	}
    	else
    	{
    		setPercentage2(100);
    		
    	}
    	getLabel3().setText("You have achieved " + (int)(percentage1) + "% of your savings goal");;
		progressBar1.setValue((int)(result));
    }
    
    public static void updateProgressBar2()
    {
    	double totalExpense = Expenses.getObject().getTotalExpense();
    	double totalIncome = Income.getObject().getTotalIncome();
    	double savingGoal = Saving.getGoal();
    	
    	double result = (totalExpense / (totalIncome - savingGoal)) * 100;
    	
    	if(result <= 100)
    	{
    		setPercentage2(result);
    	}
    	else
    	{
    		setPercentage2(100);
    		
    	}
    	getLabel4().setText("You have achieved " + (int)(percentage2) + "% of your expenditure limit");;
		progressBar2.setValue((int)(result));
    }
    
    public static void updatePieChart()
    {
    	getTimeBox().setSelectedIndex(0);
		getSlices().get(0).setValue(Expenses.getObject().getTotalExpense());
		getSlices().get(1).setValue(Income.getObject().getTotalIncome());
		
		double totalSavings = Income.getObject().getTotalIncome() - Expenses.getObject().getTotalExpense();
		
		if(totalSavings > 0)
			getSlices().get(2).setValue(totalSavings);
		else
			getSlices().get(2).setValue(0);
		
		getPieChart().repaint();
    }
   
    /**
     	Accesses the piechart of home panel
     */
    public static PieChart getPieChart()
    {
    	return pieChart1;
    }
        
    public static ArrayList<Slice> getSlices()
    {
        return slices;
   }
    
	 /**
	 	Sets the piechart of home panel
	 */
	public void setPieChart(ArrayList<Slice> newSlices)
	{
		for(Slice s : newSlices)
		{
			slices.add(s);
		}
		repaint();
	}
	
	
	
	/**
	 	Access to the panel in wchih piechart is located
	 */
	public JPanel getPanel1()
	{
		return jPanel1;
	}
	
	
	public static JButton getExpBtn()
	{
		return addExpense;
	}
	
	public static JButton getIncBtn()
	{
		return addIncome;
	}
	
	public static DefaultListModel<String> getListModel()
	{
		return model;
	}
	
	public static JProgressBar getProgressBar1()
	{
		return progressBar1;
	}
	
	public static double getPercentage1()
	{
		return percentage1;
	}
	
	public static void setPercentage1(double percentage)
	{
		percentage1 = percentage;
	}
	
	public static JLabel getLabel3()
	{
		return label3;
	}
	
	public static JProgressBar getProgressBar2()
	{
		return progressBar2;
	}
	
	public static double getPercentage2()
	{
		return percentage2;
	}
	
	public static void setPercentage2(double percentage)
	{
		percentage2 = percentage;
	}
	
	public static JLabel getLabel4()
	{
		return label4;
	}
	
	public static JComboBox<String> getTimeBox()
	{
		return timely;
	}

	public static ArrayList<Reminder> getReminders() 
	{
		return reminders;
	}
	
}
